### PR TITLE
add libraries (ggplot2, epidemics, webshot) to episode

### LINKED ISSUE #1: ERROR in functions `population`, `no_vaccination`, `model_vacamole_cpp`, `ggplot`
In challenge we are getting an error

https://epiverse-trace.github.io/tutorials-late/compare-interventions.html#challenge-ebola-outbreak-analysis

code in

https://github.com/epiverse-trace/tutorials-late/blob/da599e195940aa85b0f885d0d39ba190885c8221/episodes/compare-interventions.Rmd#L203-L224

### PR DESCRIPTION
**Pull request by avallecam**
Fix #1

### CODE REVIEW

**Comment by avallecam** [comment]
hi @Bisaloo , brief review request. 

Also, an opportunity to ask, how to put "Rebase and merge" as the default for merge? should this change after merging this or we can set this up in the Settings of the repo?

**Comment by avallecam** [comment]
@Bisaloo also, while looking at the `md-output` for [compare-interventions](https://github.com/epiverse-trace/tutorials-late/blob/md-outputs-PR-2/compare-interventions.md#vacamole-model), the section that generates a diagram with {DiagrammeR} generates a weird output. Can you see it? This is the first time I've noticed this in this episode. 

the [simulating-transmission](https://github.com/epiverse-trace/tutorials-late/blob/md-outputs-PR-2/simulating-transmission.md#simulating-disease-spread) episode, that also uses {DiagrammeR} seems to deploy ok.

In order to make the printing of {DiagrammeR} visible on the workbench, we are using `webshot::install_phantomjs(force = TRUE)`. Please see [this comment and reference link](https://github.com/epiverse-trace/tutorials/issues/98#issuecomment-1865988495) 

{webshot} is present in `simulating-transmission` but not in `compare-interventions`, should we try to add it there to see if this fix the md output?

**Comment by Bisaloo** [comment]
> Also, an opportunity to ask, how to put "Rebase and merge" as the default for merge? should this change after merging this or we can set this up in the Settings of the repo?

The default is user-specific and it corresponds to the latest setting you used in a specific repo. We cannot set it for all the users.

**Comment by Bisaloo** [comment]
> {DiagrammeR} generates a weird output. Can you see it? This is the first time I've noticed this in this episode.
> 
> the [simulating-transmission](https://github.com/epiverse-trace/tutorials-late/blob/md-outputs-PR-2/simulating-transmission.md?rgh-link-date=2024-02-16T19%3A01%3A56Z#simulating-disease-spread) episode, that also uses {DiagrammeR} seems to deploy ok.
> 
> In order to make the printing of {DiagrammeR} visible on the workbench, we are using `webshot::install_phantomjs(force = TRUE)`. Please see [this comment and reference link](https://github.com/epiverse-trace/tutorials/issues/98#issuecomment-1865988495)
> 
> {webshot} is present in `simulating-transmission` but not in `compare-interventions`, should we try to add it there to see if this fix the md output?

My understanding is that it will still work fine on `main` because all episodes are re-rendered and webshot will already be loaded + phanthomjs already installed.
We can also add it to `simulation-transmission` to make sure that PR previews look good as well.

**Review by Bisaloo — APPROVED** [review]

**Comment by avallecam** [comment]
@Bisaloo I confirm that adding {webshot} within the Rmd file allows us to have clean `md-outputs` when using {Diagrammer} as in [compare-interventions](https://github.com/epiverse-trace/tutorials-late/blob/md-outputs-PR-2/compare-interventions.md#vacamole-model) episode.

My take-home message is that each episode is independent with respect to the package dependencies loaded. For this reason, we got issues with {epidemics} and {ggplot} in this episode only.

Ready to rebase and merge 🚀

**Pull request merged**
